name: run-workflows
on:
  push: 
    branches:
      - main
    paths:
      - workflows/**
  pull_request:
    branches:
      - main
    paths:
      - workflows/**
  schedule:
      - cron: "0 0/2 * * *"
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.8"
    - name: pip install
      run: pip install -r requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: install azmlcli
      run: az extension add -n azure-cli-ml
    - name: attach to workspace
      run: az ml folder attach -w default -g azureml-template
    - name: run basic job
      run: python workflows/basic/job.py
